services:
  lab:
    build: .
    working_dir: /workspace
    environment:
      GRADLE: "sh ./gradlew --no-daemon"
    volumes:
      - .:/workspace
      - gradle-cache:/opt/gradle-cache
      - project-gradle:/workspace/Tai-e/.gradle
      - buildsrc-gradle:/workspace/Tai-e/buildSrc/.gradle

volumes:
  gradle-cache:
  project-gradle:
  buildsrc-gradle:
